[package]
name = "serde_datalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.13"
rusqlite = "0.30.0"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
