[package]
name = "serde_datalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
erased-serde = "0.4.2"
ron = "0.8.1"
rusqlite = "0.30.0"
serde = { version = "1.0.194", features = ["derive"] }
serde-transcode = "1.1.1"
serde_json = "1.0.111"
toml = "0.8.8"

[lib]
name = "serde_datalog"
path = "src/lib.rs"

[[bin]]
name = "serdedl"
path = "src/main.rs"
