//! A backend that stores facts as vectors of tuples.

use bimap::BiHashMap;
use delegate::delegate;
use std::{
    collections::HashMap,
    fmt::{Debug, Display},
    hash::Hash,
};

use crate::{DatalogExtractionError, DatalogExtractorBackend, ElemId, ElemType, Result};

/// Identifier for an interned string.
#[derive(PartialEq, Eq, Hash, Clone, Copy, Debug)]
pub struct SymbolId(pub usize);

impl Display for SymbolId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

const BOOL_NAME: &str = "Bool";
const NUMBER_NAME: &str = "Number";
const STR_NAME: &str = "Str";
const MAP_NAME: &str = "Map";
const SEQ_NAME: &str = "Seq";
const STRUCT_NAME: &str = "Struct";
const STRUCT_VARIANT_NAME: &str = "StructVariant";
const TUPLE_NAME: &str = "Tuple";
const TUPLE_STRUCT_NAME: &str = "TupleStruct";
const TUPLE_VARIANT_NAME: &str = "TupleVariant";
const UNIT_NAME: &str = "Unit";
const UNIT_STRUCT_NAME: &str = "UnitStruct";
const UNIT_VARIANT_NAME: &str = "UnitVariant";

/// Table data generated by vector backends.
pub struct BackendData<K: Eq + Hash> {
    pub symbol_table: BiHashMap<String, SymbolId>,

    /// Stores root elemets of files.
    pub root_elem_table: HashMap<SymbolId, ElemId>,

    /// Stores types of elements.
    /// Columns: (elem, elem type)
    pub type_table: HashMap<ElemId, SymbolId>,

    /// Stores values of boolean elements.
    /// Columns: (elem, value)
    pub bool_table: HashMap<ElemId, bool>,

    /// Stores values of number elements.
    /// Columns: (elem, value)
    pub number_table: HashMap<ElemId, isize>,

    /// Stores values of string elements.
    /// Columns: (elem, symbol)
    pub string_table: HashMap<ElemId, SymbolId>,

    /// Stores map entry facts.
    /// Columns: (elem, key, value)
    pub map_table: HashMap<(ElemId, K), ElemId>,

    /// Stores type names of structs.
    /// Columns: (elem, struct name)
    pub struct_type_table: HashMap<ElemId, SymbolId>,

    /// Stores struct field facts.
    /// Columns: (elem, field name, value elem)
    pub struct_table: HashMap<(ElemId, SymbolId), ElemId>,

    /// Stores sequence entry facts.
    /// Columns: (elem, index, value)
    pub seq_table: HashMap<(ElemId, usize), ElemId>,

    /// Stores type and variant names of variant elements.
    /// (elem, enum name, variant name)
    pub variant_type_table: HashMap<ElemId, (SymbolId, SymbolId)>,

    /// Stores tuple entry facts.
    /// Columns: (elem, index, value)
    pub tuple_table: HashMap<(ElemId, usize), ElemId>,
}

impl<K: Display + Eq + Hash> Default for BackendData<K> {
    fn default() -> Self {
        Self {
            symbol_table: Default::default(),
            root_elem_table: Default::default(),
            type_table: Default::default(),
            bool_table: Default::default(),
            number_table: Default::default(),
            string_table: Default::default(),
            map_table: Default::default(),
            struct_type_table: Default::default(),
            struct_table: Default::default(),
            seq_table: Default::default(),
            variant_type_table: Default::default(),
            tuple_table: Default::default(),
        }
    }
}

impl<K: Eq + Hash> BackendData<K> {
    /// Print generated fact tables to standard output.
    pub fn dump_with_fn<'a, S: Display>(&'a self, map_key_fn: impl Fn(&'a Self, &'a K) -> S)
    where K: 'a, S: 'a
    {
        if !self.symbol_table.is_empty() {
            println!("{:^33}", "Symbol Table");
            println!("---------------------------------");
            println!("{:<15} | {:<15}", "String", "Symbol Id");
            println!("---------------------------------");
            for (str, sym) in self.symbol_table.iter() {
                println!("{:<15} | {:<15}", str, sym.0);
            }
            println!();
        }

        if !self.root_elem_table.is_empty() {
            println!("{:^33}", "Root Elem Table");
            println!("---------------------------------");
            println!("{:<15} | {:<15}", "File", "Elem Id");
            println!("---------------------------------");
            for (file, elem) in self.root_elem_table.iter() {
                println!("{:<15} | {:<15}", file.0, elem.0);
            }
            println!();
        }

        if !self.type_table.is_empty() {
            println!("{:^33}", "Type Table");
            println!("---------------------------------");
            println!("{:<15} | {:<15}", "Elem Id", "Elem Type");
            println!("---------------------------------");
            for (elem, elem_type) in self.type_table.iter() {
                println!("{:<15} | {:<15}", elem.0, elem_type.0);
            }
            println!();
        }

        if !self.bool_table.is_empty() {
            println!("{:^33}", "Bool Table");
            println!("---------------------------------");
            println!("{:<15} | {:<15}", "Elem Id", "Value");
            println!("---------------------------------");
            for (elem, value) in self.bool_table.iter() {
                println!("{:<15} | {:<15}", elem.0, value);
            }
            println!();
        }

        if !self.number_table.is_empty() {
            println!("{:^33}", "Number Table");
            println!("---------------------------------");
            println!("{:<15} | {:<15}", "Elem Id", "Value");
            println!("---------------------------------");
            for (elem, value) in self.number_table.iter() {
                println!("{:<15} | {:<15}", elem.0, value);
            }
            println!();
        }

        if !self.string_table.is_empty() {
            println!("{:^33}", "String Table");
            println!("---------------------------------");
            println!("{:<15} | {:<15}", "Elem Id", "Value");
            println!("---------------------------------");
            for (elem, value) in self.string_table.iter() {
                println!("{:<15} | {:<15}", elem.0, value.0);
            }
            println!();
        }

        if !self.map_table.is_empty() {
            println!("{:^51}", "Map Table");
            println!("---------------------------------------------------");
            println!("{:<15} | {:<15} | {:<15}", "Elem Id", "Key", "Value");
            println!("---------------------------------------------------");
            for ((elem, key), val) in self.map_table.iter() {
                println!("{:<15} | {:<15} | {:<15}", elem.0, map_key_fn(self, key), val.0);
            }
            println!();
        }

        if !self.struct_type_table.is_empty() {
            println!("{:^33}", "Struct Type Table");
            println!("---------------------------------");
            println!("{:<15} | {:<15}", "Elem Id", "Struct Type");
            println!("---------------------------------");
            for (elem, struct_type) in self.string_table.iter() {
                println!("{:<15} | {:<15?}", elem.0, struct_type.0);
            }
            println!();
        }

        if !self.struct_table.is_empty() {
            println!("{:^51}", "Struct Field Table");
            println!("---------------------------------------------------");
            println!("{:<15} | {:<15} | {:<15}", "Elem Id", "Field", "Value");
            println!("---------------------------------------------------");
            for ((elem, field), val) in self.struct_table.iter() {
                println!(
                    "{:<15} | {:<15} | {:<15}",
                    elem.0,
                    self.symbol_table.get_by_right(field).unwrap(),
                    val.0
                );
            }
            println!();
        }

        if !self.seq_table.is_empty() {
            println!("{:^51}", "Seq Table");
            println!("---------------------------------------------------");
            println!("{:<15} | {:<15} | {:<15}", "Elem Id", "Index", "Value");
            println!("---------------------------------------------------");
            for ((elem, index), val) in self.seq_table.iter() {
                println!("{:<15} | {:<15} | {:<15}", elem.0, index, val.0);
            }
            println!();
        }

        if !self.variant_type_table.is_empty() {
            println!("{:^51}", "Variant Type Table");
            println!("---------------------------------------------------");
            println!(
                "{:<15} | {:<15} | {:<15}",
                "Elem Id", "Enum Type", "Variant Name"
            );
            println!("---------------------------------------------------");
            for (elem, (enum_type, variant_name)) in self.variant_type_table.iter() {
                println!(
                    "{:<15} | {:<15} | {:<15}",
                    elem.0,
                    self.symbol_table.get_by_right(enum_type).unwrap(),
                    self.symbol_table.get_by_right(variant_name).unwrap(),
                );
            }
            println!();
        }

        if !self.tuple_table.is_empty() {
            println!("{:^51}", "Tuple Table");
            println!("---------------------------------------------------");
            println!("{:<15} | {:<15} | {:<15}", "Elem Id", "Index", "Value");
            println!("---------------------------------------------------");
            for ((elem, index), val) in self.tuple_table.iter() {
                println!("{:<15} | {:<15?} | {:<15?}", elem.0, index, val.0);
            }
            println!();
        }
    }

    /// dump function that does not require a printing function for map keys;
    /// this can only be called when map key type `K` implements [Display].
    pub fn dump(&self) where K: Display {
        self.dump_with_fn(|_, key| key)
    }
}

/// DatalogExtractorBackend impl that stores facts in vectors.
/// Note that this backend interns strings, so tables store a string's
/// [SymbolId] instead of the string itself.
///
/// Note that this backend does **not** support extraction of
/// floating point values, and will return a
/// [UnextractableData][DatalogExtractionError::UnextractableData] error if
/// the input contains such values.
struct AbstractBackend<K: Display + Eq + Hash> {
    pub(crate) cur_symbol_id: SymbolId,
    pub(crate) data: BackendData<K>,
}

impl<K: Display + Eq + Hash> Default for AbstractBackend<K> {
    fn default() -> Self {
        let mut backend = Self {
            cur_symbol_id: SymbolId(1),
            data: Default::default(),
        };

        backend.intern_string(BOOL_NAME);
        backend.intern_string(NUMBER_NAME);
        backend.intern_string(STR_NAME);
        backend.intern_string(MAP_NAME);
        backend.intern_string(SEQ_NAME);
        backend.intern_string(STRUCT_NAME);
        backend.intern_string(STRUCT_VARIANT_NAME);
        backend.intern_string(TUPLE_NAME);
        backend.intern_string(TUPLE_STRUCT_NAME);
        backend.intern_string(TUPLE_VARIANT_NAME);
        backend.intern_string(UNIT_NAME);
        backend.intern_string(UNIT_STRUCT_NAME);
        backend.intern_string(UNIT_VARIANT_NAME);

        backend
    }
}

impl<K: Display + Eq + Hash> AbstractBackend<K> {
    fn intern_string(&mut self, s: &str) -> SymbolId {
        match self.data.symbol_table.get_by_left(s) {
            Some(id) => *id,
            None => {
                let SymbolId(id) = self.cur_symbol_id;
                self.data
                    .symbol_table
                    .insert(s.to_string(), self.cur_symbol_id);
                self.cur_symbol_id.0 += 1;
                SymbolId(id)
            }
        }
    }

    fn get_data(self) -> BackendData<K> {
        self.data
    }

    fn process_prev_value<T>(elem: ElemId, prev: Option<T>) -> Result<()> {
        prev.map_or(Result::Ok(()), |_| {
            Result::Err(DatalogExtractionError::NonuniqueIdentifier(elem))
        })
    }

    fn add_root_elem(&mut self, file: &str, elem: ElemId) -> Result<()> {
        let sym = self.intern_string(file);

        Self::process_prev_value(elem, self.data.root_elem_table.insert(sym, elem))
    }

    fn add_elem(&mut self, elem: ElemId, elem_type: ElemType) -> Result<()> {
        let type_name: &str = match elem_type {
            ElemType::Bool => BOOL_NAME,

            ElemType::I8
            | ElemType::I16
            | ElemType::I32
            | ElemType::I64
            | ElemType::U8
            | ElemType::U16
            | ElemType::U32
            | ElemType::U64 => NUMBER_NAME,

            ElemType::Char | ElemType::Str => STR_NAME,

            ElemType::F32 | ElemType::F64 | ElemType::Bytes => {
                return Result::Err(DatalogExtractionError::UnextractableData);
            }

            ElemType::Map => MAP_NAME,
            ElemType::Seq => SEQ_NAME,
            ElemType::Struct => STRUCT_NAME,
            ElemType::StructVariant => STRUCT_VARIANT_NAME,
            ElemType::Tuple => TUPLE_NAME,
            ElemType::TupleStruct | ElemType::NewtypeStruct => TUPLE_STRUCT_NAME,

            ElemType::TupleVariant | ElemType::NewtypeVariant => TUPLE_VARIANT_NAME,

            ElemType::Unit => UNIT_NAME,
            ElemType::UnitStruct => UNIT_STRUCT_NAME,
            ElemType::UnitVariant => UNIT_VARIANT_NAME,
        };

        let elem_type_sym = self.intern_string(type_name);
        Self::process_prev_value(elem, self.data.type_table.insert(elem, elem_type_sym))
    }

    fn add_bool(&mut self, elem: ElemId, value: bool) -> Result<()> {
        Self::process_prev_value(elem, self.data.bool_table.insert(elem, value))
    }

    fn add_i64(&mut self, elem: ElemId, value: i64) -> Result<()> {
        Self::process_prev_value(elem, self.data.number_table.insert(elem, value as isize))
    }

    fn add_u64(&mut self, elem: ElemId, value: u64) -> Result<()> {
        Self::process_prev_value(elem, self.data.number_table.insert(elem, value as isize))
    }

    fn add_f64(&mut self, _elem: ElemId, _value: f64) -> Result<()> {
        Result::Err(DatalogExtractionError::UnextractableData)
    }

    fn add_bytes(&mut self, _elem: ElemId, _value: &[u8]) -> Result<()> {
        Result::Err(DatalogExtractionError::UnextractableData)
    }

    fn add_str(&mut self, elem: ElemId, value: &str) -> Result<()> {
        let value_sym = self.intern_string(value);
        Self::process_prev_value(elem, self.data.string_table.insert(elem, value_sym))
    }

    fn add_struct_type(&mut self, elem: ElemId, struct_name: &str) -> Result<()> {
        let struct_name_sym = self.intern_string(struct_name);
        Self::process_prev_value(
            elem,
            self.data.struct_type_table.insert(elem, struct_name_sym),
        )
    }

    fn add_struct_entry(&mut self, elem: ElemId, key: &str, value: ElemId) -> Result<()> {
        let key_sym = self.intern_string(key);
        Self::process_prev_value(elem, self.data.struct_table.insert((elem, key_sym), value))
    }

    fn add_seq_entry(&mut self, elem: ElemId, pos: usize, value: ElemId) -> Result<()> {
        self.data
            .seq_table
            .insert((elem, pos), value)
            .map_or(Result::Ok(()), |_| {
                Result::Err(DatalogExtractionError::NonuniqueIdentifier(elem))
            })
    }

    fn add_variant_type(
        &mut self,
        elem: ElemId,
        type_name: &str,
        variant_name: &str,
    ) -> Result<()> {
        let type_name_sym = self.intern_string(type_name);
        let variant_name_sym = self.intern_string(variant_name);
        Self::process_prev_value(
            elem,
            self.data
                .variant_type_table
                .insert(elem, (type_name_sym, variant_name_sym)),
        )
    }

    fn add_tuple_entry(&mut self, elem: ElemId, pos: usize, value: ElemId) -> Result<()> {
        Self::process_prev_value(elem, self.data.tuple_table.insert((elem, pos), value))
    }
}

/// DatalogExtractorBackend impl that stores facts as vectors of tuples.
/// Returns data of type `BackendData<ElemId>`.
#[derive(Default)]
pub struct Backend {
    parent: AbstractBackend<ElemId>,
}

impl Backend {
    /// Return data generated by the backend.
    pub fn get_data(self) -> BackendData<ElemId> {
        self.parent.get_data()
    }

    /// Print generate fact tables to standard output.
    pub fn dump(self) {
        self.parent.get_data().dump()
    }
}

impl DatalogExtractorBackend for Backend {
    delegate! {
        to self.parent {
            fn add_root_elem(&mut self, file: &str, elem: ElemId) -> Result<()>;
            fn add_elem(&mut self, elem: ElemId, elem_type: ElemType) -> Result<()>;
            fn add_bool(&mut self, elem: ElemId, value: bool) -> Result<()>;
            fn add_i64(&mut self, elem: ElemId, value: i64) -> Result<()>;
            fn add_u64(&mut self, elem: ElemId, value: u64) -> Result<()>;
            fn add_f64(&mut self, elem: ElemId, value: f64) -> Result<()>;
            fn add_str(&mut self, elem: ElemId, value: &str) -> Result<()>;

            /// This backend does not support extracting byte arrays.
            fn add_bytes(&mut self, elem: ElemId, value: &[u8]) -> Result<()>;

            fn add_struct_type(&mut self, elem: ElemId, struct_name: &str) -> Result<()>;
            fn add_struct_entry(&mut self, elem: ElemId, key: &str, value: ElemId) -> Result<()>;
            fn add_seq_entry(&mut self, elem: ElemId, pos: usize, value: ElemId) -> Result<()>;
            fn add_variant_type(&mut self, elem: ElemId, type_name: &str, variant_name: &str) -> Result<()>;
            fn add_tuple_entry(&mut self, elem: ElemId, pos: usize, value: ElemId) -> Result<()>;
        }
    }

    fn add_map_entry(&mut self, elem: ElemId, key: ElemId, value: ElemId) -> Result<()> {
        AbstractBackend::<ElemId>::process_prev_value(
            elem,
            self.parent.data.map_table.insert((elem, key), value),
        )
    }
}

/// DatalogExtractorBackend impl similar to [Backend], except this impl assumes
/// map keys are always strings. Returns data of type `BackendData<SymbolId>`.
#[derive(Default)]
pub struct StringKeyBackend {
    parent: AbstractBackend<SymbolId>,
}

impl StringKeyBackend {
    /// Return data generated by the backend.
    pub fn get_data(self) -> BackendData<SymbolId> {
        self.parent.get_data()
    }

    /// Print generate fact tables to standard output.
    pub fn dump(self) {
        self.parent.get_data().dump_with_fn(|data, key| {
            data.symbol_table.get_by_right(key).unwrap()
        })
    }
}

impl DatalogExtractorBackend for StringKeyBackend {
    delegate! {
        to self.parent {
            fn add_root_elem(&mut self, file: &str, elem: ElemId) -> Result<()>;
            fn add_elem(&mut self, elem: ElemId, elem_type: ElemType) -> Result<()>;
            fn add_bool(&mut self, elem: ElemId, value: bool) -> Result<()>;
            fn add_i64(&mut self, elem: ElemId, value: i64) -> Result<()>;
            fn add_u64(&mut self, elem: ElemId, value: u64) -> Result<()>;
            fn add_f64(&mut self, elem: ElemId, value: f64) -> Result<()>;
            fn add_str(&mut self, elem: ElemId, value: &str) -> Result<()>;

            /// This backend does not support extracting byte arrays.
            fn add_bytes(&mut self, elem: ElemId, value: &[u8]) -> Result<()>;

            fn add_struct_type(&mut self, elem: ElemId, struct_name: &str) -> Result<()>;
            fn add_struct_entry(&mut self, elem: ElemId, key: &str, value: ElemId) -> Result<()>;
            fn add_seq_entry(&mut self, elem: ElemId, pos: usize, value: ElemId) -> Result<()>;
            fn add_variant_type(&mut self, elem: ElemId, type_name: &str, variant_name: &str) -> Result<()>;
            fn add_tuple_entry(&mut self, elem: ElemId, pos: usize, value: ElemId) -> Result<()>;
        }
    }

    fn add_map_entry(&mut self, elem: ElemId, key: ElemId, value: ElemId) -> Result<()> {
        if let Some(sym) = self.parent.data.string_table.remove(&key) {
            AbstractBackend::<SymbolId>::process_prev_value(
                elem,
                self.parent.data.map_table.insert((elem, sym), value),
            )
        } else {
            Result::Err(DatalogExtractionError::UnextractableData)
        }
    }
}
