// run:
// serde_dialog test1.toml -o test1_toml.db
// souffle test1_toml_query.dl

// return the dependencies of the 'rand' package defined in test1.toml
// along with their corresponding versions

#include "../schemas/toml.dl"

.decl depVersion(dep: symbol, version: symbol)
depVersion(dep, version) :-
    rootElem(root),
    tomlTable(root, "dependencies", deps),
    tomlTable(deps, dep, depRecord),
    tomlTable(depRecord, "version", versionId),
    tomlString(versionId, version).

.input type, bool, number, string, map, struct, seq, tuple, structType, variantType(IO=sqlite, dbname="test1_toml.db")
.output depVersion(IO=stdout)
